version: '3.8'


networks:
  demos:
    driver: bridge


services:

  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=demouser
      - MONGODB_ROOT_PASSWORD=demopassword
      - MONGODB_REPLICA_SET_KEY=demoreplicaset
    networks:
      - demos

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_ROOT_USER=demouser
      - MONGODB_ROOT_PASSWORD=demopassword
      - MONGODB_REPLICA_SET_KEY=demoreplicaset
    networks:
      - demos

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_ROOT_USER=demouser
      - MONGODB_ROOT_PASSWORD=demopassword
      - MONGODB_REPLICA_SET_KEY=demoreplicaset
    networks:
      - demos
